/*************************************
表名称:账户交易表
字段前缀:ACD
最后修改人:genghs
*************************************/
DROP TABLE IF EXISTS ACCOUNTRECORD;

CREATE TABLE ACCOUNTRECORD
(
	ACD_SERIALNO		VARCHAR(30)	NOT NULL,	/*流水号*/
	ACD_ACCOUNTNO		VARCHAR(20)	NOT NULL,	/*账号*/
	ACD_TRANTIME		CHAR(14)	NOT NULL,	/*交易时间*/
	ACD_TRANTYPE		CHAR(2)		NOT NULL,	/*交易类型*/
	ACD_OTHERACCOUNTNO	VARCHAR(20)	,	/*对方账号*/
	ACD_OTHERACCOUNTNAME	VARCHAR(60)	,	/*对方户名*/
	ACD_AMOUNT		DECIMAL(18,2)	NOT NULL,	/*交易金额，带正负号*/
	ACD_BALANCE		DECIMAL(18,2)	NOT NULL,	/*余额*/
	ACD_CHANNELSYSTEMNO	VARCHAR(30)	,	/*渠道系统号*/
	ACD_CHANNELSERIALNO	VARCHAR(30)	,	/*渠道流水号*/
	ACD_STATUS		VARCHAR(2)	DEFAULT 0	NOT NULL,	/*状态*/
	PRIMARY KEY (ACD_SERIALNO)
)DEFAULT CHARSET=utf8;